configuration: Release
install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - cmd: nuget install GitVersion.CommandLine -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre

assembly_info:
  patch: false
      
before_build:  
  - cmd: nuget restore
  - cmd: '.\packages\GitVersion.CommandLine\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo'
  
build:
  verbosity: normal
  project: ReferenceGenerator.sln
    
after_build:    
  - cmd: nuget pack NuSpec.ReferenceGenerator.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -basepath "artifacts"
  - cmd: appveyor PushArtifact "NuSpec.ReferenceGenerator.%GitVersion_NuGetVersion%.nupkg"